name: Build and Deploy PHP Site to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch if it's not "main"
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP runtime
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Adjust PHP version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          composer install # If you're using Composer for dependencies
          npm install # If your project has frontend dependencies (optional)

      # Step 4: Build the site
      - name: Build the site
        run: |
          php build.php # Adjust based on your build process
          # For Jigsaw:
          # ./vendor/bin/jigsaw build

      # Step 5: Upload static files as an artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build_local' # Change to the directory containing your built static files

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
